### ISSUE TITLE
Tracking and aligning ROIs and tracks

### ISSUE THREAD

**Issue by arokem** [arokem/AFQ-notebooks#2]
We're close, but still aligning is elusive. Seems to work fine for CSD tracks, but still no cigar for DTI tracks. What's that all about?

**Comment by arokem** [comment]
Seems like have it now, with CSA-based tracking: 

https://github.com/arokem/AFQ-notebooks/blob/31ebaa9ae318190b71353c3cf674aa6d0c740f83/CSA-tracking-white-matter.ipynb

**Comment by jyeatman** [comment]
The AFQ registration notebook looks good. But there seems to be an error in
the CSA-tracking, at least in how it renders on github

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
You mean the "invalid value in divide"? I think that's a benign warning,
but I will investigate!
